services:
  pgmodeler:
    image: pgmodeler:latest
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./data:/home/root/projects
    network_mode: host
